version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: ecoconnect-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecoconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - ecoconnect-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecoconnect"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplicação NestJS
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoconnect-api
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ecoconnect?schema=public"
      JWT_SECRET: "ecoconnect-jwt-secret-key-2024"
      JWT_EXPIRES_IN: "7d"
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecoconnect-network
    volumes:
      - ./prisma:/app/prisma
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node dist/main
      "

  # Adminer para gerenciamento do banco (opcional)
  adminer:
    image: adminer:latest
    container_name: ecoconnect-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ecoconnect-network
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
    driver: local

networks:
  ecoconnect-network:
    driver: bridge

